model_onestep_sr:
  target: models_v3.transformer_flux_prune_norm_0423.FluxTransformer2DModel
  params:
    patch_size: 1
    in_channels: 128
    num_layers: 34
    num_single_layers: 0
    attention_head_dim: 384
    num_attention_heads: 4
    joint_attention_dim: 1536
    pooled_projection_dim: 768
    guidance_embeds: false                                # gft: true,  cfg: false
    train_painting_sr: false
    noise_concat_lq: true
    axes_dims_rope:
      - 48
      - 168
      - 168
    processor_type: default
    ffn_ratio: 4
    adaln_dim: 1536
    pct_key: 100PCT
    # enable_skip_level: 100
    # layers_to_retained: 
    #   100:
    #     transformer_blocks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
    #   # 40和60的层数选择没有经过实验, 仅用作配置格式示范使用
    #   60:
    #     transformer_blocks: [0,2,3,6,9,12,13,14,16,18,20,22,23,24,25]
    #   40:
    #     transformer_blocks: [0,2,3,6,12,13,22,23,24,25]

# text_guided:
#   init_trainable_vector:
#     bbox_fix_tokens: False
#     ctxt_fix_tokens: False
#     seg_fix_tokens: True
#     sr_fix_tokens: True
#     t2i_fix_tokens: True
#     sun_fix_tokens: True
#     facesr_fix_tokens: True
#     sr20Xbright_fix_tokens: True
#     sr20Xdark_fix_tokens: True
#     sr50X_fix_tokens: True
#     bokeh_fix_tokens: True
#     linedraw_fix_tokens: True
#     moonsr_fix_tokens: True
#     moonpainting_fix_tokens: True
#     token_requires_grad: True